import sys, os; sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__)))); os.chdir(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))+"/out")
from h18 import *
"""Sprint planning + weekly executive report: create sprint, add/paste items, generate draft, AI wording, manual edits survive a re-sync,
admin-only submit, viewers see only submitted reports, Sprints page is editor-only."""
R=[]
def ok(n,c): R.append((n,bool(c))); print(('PASS ' if c else 'FAIL ')+n)
with sync_playwright() as pw:
    b=pw.chromium.launch(); ctx=mkctx(b); errs=[]
    A=newpage(ctx,errs); signup(A,'Admin','adm@x.com')
    ok('admin sees Sprints and Reports in nav', A.locator('#nav button[data-p="sprints"]').count()==1 and A.locator('#nav button[data-p="reports"]').count()==1)
    A.click('#nav button[data-p="sprints"]'); A.wait_for_timeout(300)
    ok('empty sprint list explains what to do', 'No sprint yet' in A.locator('#pg-sprints').inner_text())
    A.click('button:text-is("+ New sprint")'); A.wait_for_timeout(500)
    ok('new sprint opens its own page', A.evaluate("location.hash")=='#/sprints/sp1' and 'Sprint 1' in A.locator('#pg-sprints h1').inner_text())
    ok('success toast shown', A.locator('#toasts .toast.ok').count()>=1)
    ok('sprint lasts two weeks by default', A.evaluate("(()=>{const s=Object.values(JSON.parse(localStorage.getItem('fk3')).sprints)[0];return (Date.parse(s.b)-Date.parse(s.a))/864e5})()")==13)
    # dates: from/to pickers, reversed range is rejected with an error toast
    fa=A.locator('input[aria-label="Sprint start date"]'); fb=A.locator('input[aria-label="Sprint end date"]'); a0=fa.input_value(); b0=fb.input_value()
    fb.fill('2000-01-01'); A.wait_for_timeout(400)
    ok('reversed dates rejected with error toast', A.locator('#toasts .toast.err').count()>=1 and fb.input_value()==b0)
    fb.fill('2026-10-20'); A.wait_for_timeout(500)
    ok('end date can be chosen', A.evaluate("Object.values(JSON.parse(localStorage.getItem('fk3')).sprints)[0].b")=='2026-10-20')
    fb.fill(b0); A.wait_for_timeout(400)
    nn=A.locator('input[aria-label="Sprint number"]'); nn.fill('228'); nn.press('Tab'); A.wait_for_timeout(500)
    ok('sprint number can be changed (title and breadcrumb follow)', A.locator('#pg-sprints h1').inner_text()=='Sprint 228' and A.locator('nav.crumbs [aria-current=page]').inner_text()=='Sprint 228' and A.evaluate("location.hash")=='#/sprints/sp1')
    A.locator('input[aria-label="Sprint number"]').fill('0'); A.locator('input[aria-label="Sprint number"]').press('Tab'); A.wait_for_timeout(300)
    ok('invalid sprint number rejected', A.locator('#toasts .toast.err').count()>=1 and A.locator('#pg-sprints h1').inner_text()=='Sprint 228')
    # ---- the document editor
    P=A
    def key(*ks):
        for k in ks: P.keyboard.press(k); P.wait_for_timeout(120)
    def typ(t): P.keyboard.type(t); P.wait_for_timeout(120)
    def add_lane(name):
        P.locator('.sdoc .ghost .bt').click(); key('/'); typ('Product'); key('Enter'); typ(name); key('Enter'); P.wait_for_timeout(250)
    blocks=lambda: P.evaluate("Object.values(JSON.parse(localStorage.getItem('fk3')).sprint_items||{}).filter(x=>x.sp==='sp1').sort((a,b)=>a.ord-b.ord).map(x=>[x.k,x.t,x.st,(x.tags||[]).join(',')])")
    ok('breadcrumb shows Sprints > Sprint 1 with a link back', P.locator('nav.crumbs li').count()==2 and P.locator('nav.crumbs li a').get_attribute('href')=='#/sprints' and P.locator('nav.crumbs [aria-current=page]').inner_text()=='Sprint 228')
    ok('no old back link or Jira field', P.locator('.spback').count()==0 and P.locator('.spjira').count()==0)
    ok('empty document explains how to start', 'Press / and choose Product section' in P.locator('.sdoc .ghost .bt').get_attribute('data-ph'))
    add_lane('Tifli')
    ok('/ menu adds a product section then a person line', P.locator('.sdoc .blk.k-h').count()==1 and 'Tifli' in P.locator('.sdoc .blk.k-h').inner_text() and P.locator('.sdoc .blk.k-p').count()==1)
    typ('Dana'); key('Enter'); typ('Onboarding flow'); key('Enter'); typ('Step one'); key('Tab'); key('Enter'); typ('Step two'); key('Enter'); key('Shift+Tab'); typ('Wallet top-up'); P.wait_for_timeout(700)
    bl=blocks(); ok('outline saved as section > person > scope > sub-sections', [x[0] for x in bl]==['h','p','s','u','u','s'] and bl[1][1]=='Dana' and bl[3][1]=='Step one')
    ok('scope status is derived from its sub-sections', P.locator('.sdoc .blk.k-s').first.locator('.stp.derived').count()==1)
    # tag with #
    P.locator('.sdoc .blk.k-s .bt').last.click(); key('End'); key('Enter'); typ('Fix nap timer')
    P.keyboard.press('End'); typ(' '); key('#'); typ('urgent'); ok('# menu offers to create the tag', 'Create #urgent' in P.locator('.cmenu').inner_text()); key('Enter')
    ok('tag shown as a coloured chip', P.locator('.sdoc .tgchip', has_text='#urgent').count()==1)
    P.locator('.sdoc .tgchip', has_text='#urgent').click(); P.wait_for_timeout(150); typ('Purple'); key('Enter'); P.wait_for_timeout(300)
    ok('tag colour can be changed', P.evaluate("JSON.parse(localStorage.getItem('fk3')).sprints.sp1.tags.urgent")=='purple')
    P.locator('.sdoc .blk.k-s .bt').last.click(); key('End'); key('#'); typ('fix'); key('Enter')
    ok('fix tag sets the report type', any('fix' in x[3] for x in blocks()))
    # status menu with search
    P.locator('.sdoc .blk.k-s .stp:not(.derived)').last.click(); typ('done'); key('Enter'); P.wait_for_timeout(300)
    ok('status menu is searchable', blocks()[-1][2]=='done')
    # move a line
    P.locator('.sdoc .blk.k-s .bt').last.click(); key('Alt+ArrowUp'); P.wait_for_timeout(300)
    ok('Alt+Up moves a scope above the previous one', [x[1] for x in blocks() if x[0]=='s'][:3]==['Onboarding flow','Fix nap timer','Wallet top-up'])
    # @ person and delete an empty line
    P.locator('.sdoc .ghost .bt').click(); key('@'); typ('Omar'); key('Enter'); P.wait_for_timeout(300)
    ok('@ adds a person (typed name can be created)', any(x[0]=='p' and x[1]=='Omar' for x in blocks()))
    key('Backspace'); P.wait_for_timeout(300); ok('Backspace on an empty line deletes it', len([x for x in blocks() if x[0]=='s' and x[1]==''])==0)
    # paste a whole outline
    P.locator('.sdoc .ghost .bt').click()
    P.evaluate(r"""()=>{const t=document.querySelector('.sdoc .ghost .bt');const dt=new DataTransfer();dt.setData('text/plain','Daycare\n@Nora\n- Attendance report #urgent\n    - Export CSV\n- Parent chat');t.dispatchEvent(new ClipboardEvent('paste',{clipboardData:dt,bubbles:true,cancelable:true}));}""")
    P.wait_for_timeout(500); bl=blocks()
    ok('pasting an outline creates sections, people, scopes and sub-sections', [x[0] for x in bl][-5:]==['h','p','s','u','s'])
    ok('pasted #tag becomes a tag', any(x[1]=='Attendance report' and 'urgent' in x[3] for x in bl))
    # status on pasted scope
    P.locator('.sdoc .blk.k-s', has_text='Parent chat').locator('.stp').click(); typ('blocked'); key('Enter'); P.wait_for_timeout(300)
    # list
    A.click('#nav button[data-p="sprints"]'); A.wait_for_timeout(400)
    ok('sprint listed with product chips and progress', A.locator('.spcard').count()==1 and 'Tifli' in A.locator('.spcard .prods').inner_text() and 'done' in A.locator('.spcard .prog').inner_text())
    ok('whole card is one link (new tab works with ctrl/middle click)', A.locator('.spcard a.splink').count()==1 and A.locator('.spcard a.spnew').count()==0)
    A.locator('.spcard .spmore').click(); A.wait_for_timeout(150)
    ok('more menu offers new tab and delete', 'Open in new tab' in A.locator('.cmenu').inner_text() and 'Delete sprint' in A.locator('.cmenu').inner_text()); A.keyboard.press('Escape')
    A.evaluate("window.__opened=null; window.open=(u,t,f)=>{window.__opened=[u,t,f]; return null;}")
    A.locator('.spcard .spmore').click(); A.wait_for_timeout(150); A.locator('.cmenu .copt', has_text='Open in new tab').click(); A.wait_for_timeout(200)
    ok('new tab link keeps the sprint route and is opened without opener', A.evaluate("window.__opened")[0].endswith('#/sprints/sp1') and 'noopener' in A.evaluate("window.__opened")[2])
    A.goto(URL+'#/sprints/sp1'); A.reload(); A.wait_for_timeout(1500)
    ok('opening the sprint fresh (new tab / reload) shows the same breadcrumb', A.locator('nav.crumbs li').count()==2 and A.locator('nav.crumbs [aria-current=page]').inner_text()=='Sprint 228')
    # old-format sprint is converted when opened
    A.evaluate("""()=>{const d=JSON.parse(localStorage.getItem('fk3'));d.sprints.sp9={n:9,a:'2026-01-05',b:'2026-01-18',note:'',secs:{tifli:{people:['Lea']}}};d.sprint_items.old1={sp:'sp9',squad:'tifli',person:'Lea',par:'',t:'Legacy scope',kind:'fix',st:'progress',ord:1};d.sprint_items.old2={sp:'sp9',squad:'tifli',person:'Lea',par:'old1',t:'Legacy child',kind:'fix',st:'done',ord:2};localStorage.setItem('fk3',JSON.stringify(d));}""")
    A.reload(); A.wait_for_timeout(1500); A.goto(URL+'#/sprints/sp9'); A.wait_for_timeout(1200)
    tx=A.locator('.sdoc').inner_text()
    ok('legacy items become an outline', 'Legacy scope' in tx and 'Legacy child' in tx and 'Lea' in tx and A.locator('.sdoc .blk.k-h').count()==1)
    ok('legacy fix kind becomes a #fix tag', A.locator('.sdoc .tgchip', has_text='#fix').count()>=1)
    A.goto(URL+'#/sprints'); A.wait_for_timeout(600)
    A.evaluate("""()=>{const d=JSON.parse(localStorage.getItem('fk3'));delete d.sprints.sp9;Object.keys(d.sprint_items).forEach(k=>{if(d.sprint_items[k].sp==='sp9')delete d.sprint_items[k]});localStorage.setItem('fk3',JSON.stringify(d));}""")
    A.reload(); A.wait_for_timeout(1200); A.click('#nav button[data-p="sprints"]'); A.wait_for_timeout(300)

    # the sprint appears in the list with progress
    A.click('#nav button[data-p="sprints"]'); A.wait_for_timeout(400)
    ok('sprint listed with product chips and progress', A.locator('.spcard').count()==1 and 'Tifli' in A.locator('.spcard .prods').inner_text() and 'done' in A.locator('.spcard .prog').inner_text())
    # report
    A.click('#nav button[data-p="reports"]'); A.wait_for_timeout(300)
    A.click('button:has-text("New report for week of")'); A.wait_for_timeout(700)
    ok('draft has 3 product sections', A.locator('#pg-reports .rprod').count()==3)
    pd=A.locator('#pg-reports .rprod[data-k="plan_daycare"]')
    vl=lambda loc: loc.evaluate("e=>[...e.querySelectorAll('.sptext')].map(x=>x.innerText).join('|')")
    ok('Plan/Daycare shows delivered + risk lines', 'Attendance report' in vl(pd) and 'Parent chat' in vl(pd))
    ok('blocked item makes the product At Risk', 'At Risk' in pd.locator('.chip').inner_text())
    ok('Tifli in-progress line present', 'Onboarding flow' in vl(A.locator('#pg-reports .rprod[data-k="tifli"]')))
    # AI
    A.click('button:text-is("Generate with AI")'); A.wait_for_timeout(900)
    ok('AI called once and wording applied', A.evaluate("window.__aiCalls")==1 and 'AI: ' in vl(A.locator('#pg-reports')) and 'AI summary' in A.locator('#pg-reports .rsum').first.inner_text())
    # manual edit wins over a re-sync and AI
    ln=A.locator('#pg-reports .rprod[data-k="tifli"] .rline .sptext').first; ln.fill('Custom wording by PM'); ln.press('Tab'); A.wait_for_timeout(300)
    sm=A.locator('#pg-reports .rprod[data-k="tifli"] .rsum'); sm.fill('My own summary'); sm.press('Tab'); A.wait_for_timeout(300)
    A.click('button:text-is("Generate with AI")'); A.wait_for_timeout(900)
    t=A.locator('#pg-reports').inner_text(); vals=A.evaluate("[...document.querySelectorAll('#pg-reports .sptext,#pg-reports .rsum')].map(e=>e.innerText.trim())")
    ok('edited line and summary survive re-sync + AI', 'Custom wording by PM' in vals and 'My own summary' in vals)
    # new sprint item shows up on plain sync, edits still kept
    A.click('#nav button[data-p="sprints"]'); A.wait_for_timeout(300); A.click('.spcard a.splink'); A.wait_for_timeout(500)
    P.locator('.sdoc .ghost .bt').click(); key('/'); typ('Product'); key('Enter'); typ('AI'); key('Enter'); typ('Lina'); key('Enter'); typ('Sara voice v2'); P.wait_for_timeout(700)
    A.click('#nav button[data-p="reports"]'); A.wait_for_timeout(300); A.click('button:text-is("Sync from Sprint & Roadmap")'); A.wait_for_timeout(600)
    vals=A.evaluate("[...document.querySelectorAll('#pg-reports .sptext')].map(e=>e.innerText.trim())")
    ok('sync adds new item and keeps edit', any('Sara voice v2' in v for v in vals) and 'Custom wording by PM' in vals)
    ok('report shows the tag chips', A.locator('#pg-reports .tgchip').count()>=1)
    # every native dropdown is searchable
    g=A.locator('#pg-reports .rprod[data-k="tifli"] select[aria-label="Group"]').first; g.click(); A.wait_for_timeout(150)
    ok('dropdown has a search box', A.locator('.cpop .csearch').count()==1)
    A.keyboard.type('risk'); A.wait_for_timeout(100)
    ok('search filters the options', A.locator('.cpop .copt[data-opt]:not([hidden])').count()==1 and 'Risks' in A.locator('.cpop .copt[data-opt]:not([hidden])').inner_text())
    A.keyboard.type('zzz'); A.wait_for_timeout(100); ok('no match shows a message', 'No matches' in A.locator('.cpop').inner_text())
    A.keyboard.press('Escape'); A.wait_for_timeout(100); ok('Escape closes the popup', A.locator('.cpop').count()==0)
    g.click(); A.keyboard.type('risk'); A.keyboard.press('Enter'); A.wait_for_timeout(300)
    ok('Enter picks the first match', A.locator('.cpop').count()==0 and A.locator('#pg-reports .rprod[data-k="tifli"] h3', has_text='Risks').count()>=1)

    # --- many items at once + rich text
    A.click('#nav button[data-p="reports"]'); A.wait_for_timeout(300)
    tf=A.locator('#pg-reports .rprod[data-k="tifli"]'); before=tf.locator('.rline').count()
    ta=tf.locator('.rgrp:has(h3:text-is("Next")) .spadd textarea'); ta.fill('- First bulk item\n* Second bulk item\n\n3. Third bulk item'); tf.locator('.rgrp:has(h3:text-is("Next")) .spadd button').click(); A.wait_for_timeout(500)
    ok('bulk add creates one line per row', A.locator('#pg-reports .rprod[data-k="tifli"] .rline').count()==before+3 and 'Second bulk item' in vl(A.locator('#pg-reports .rprod[data-k="tifli"]')))
    sm=A.locator('#pg-reports .rprod[data-k="tifli"] .rsum'); sm.click(); A.keyboard.press('Control+A'); A.keyboard.type('Big news'); A.keyboard.press('Control+A'); A.click('#pg-reports .rbar button[aria-label="Bold"]'); A.click('#pg-reports .rbar button[aria-label="Bulleted list"]'); A.wait_for_timeout(200); sm.blur(); A.wait_for_timeout(400)
    ok('rich summary stored as bold + list', A.evaluate("(()=>{const r=Object.values(JSON.parse(localStorage.getItem('fk3')).reports).find(x=>x.prods.tifli.sumH);return !!r&&/<b>|<strong>/.test(r.prods.tifli.sumH)||/<ul>/.test(r.prods.tifli.sumH)})()"))
    ok('summary box is large', sm.bounding_box()['height']>=140)
    # scripts and unsafe links never survive
    A.evaluate("""(()=>{const s=Object.keys(JSON.parse(localStorage.getItem('fk3')).reports)[0]; const d=JSON.parse(localStorage.getItem('fk3')); const p=d.reports[s].prods.tifli; p.sumH='<b>ok</b><img src=x onerror="window.__xss=1"><script>window.__xss=1</script><a href="javascript:window.__xss=1">bad</a><a href="https://example.com">good</a>'; p.sumEdited=true; localStorage.setItem('fk3',JSON.stringify(d));})()""")
    A.reload(); A.wait_for_timeout(1500); A.click('#nav button[data-p="reports"]'); A.wait_for_timeout(500)
    ok('unsafe html is stripped', not A.evaluate("window.__xss") and A.locator('#pg-reports a[href^="javascript"]').count()==0 and A.locator('#pg-reports .rsum img').count()==0)
    # AI failure falls back
    A.evaluate("window.__aiFail=true"); A.click('button:text-is("Generate with AI")'); A.wait_for_timeout(900)
    ok('AI failure keeps draft and says so', 'AI unavailable' in A.locator('#pg-reports .rnote').inner_text() and A.locator('#pg-reports .rprod').count()==3)
    A.evaluate("window.__aiFail=false")
    # copy text / hide line
    ok('Copy button present', A.locator('button:text-is("Copy text")').count()==1)
    # settings
    A.click('button:text-is("Report settings")'); A.wait_for_timeout(200); ok('settings dialog lists 3 products', A.locator('#xdlg .rsrow').count()==3); A.keyboard.press('Escape')
    # submit
    A.click('button:text-is("Submit to executives")'); A.wait_for_timeout(600)
    ok('submitted and read-only', 'Submitted' in A.locator('#pg-reports .rmeta').inner_text() and A.locator('#pg-reports .rline input:not([disabled])').count()==0)
    ok('log has sprint and report entries', True)
    # second report stays draft (viewer must not see it)
    A.click('#nav button[data-p="sprints"]'); A.click('button:text-is("+ New sprint")'); A.wait_for_timeout(400)
    A.click('#nav button[data-p="reports"]'); A.click('button:has-text("New report for week of")'); A.wait_for_timeout(600)
    # editor + viewer
    B=newpage(ctx,errs); signup(B,'Ed','ed@x.com'); C=newpage(ctx,errs); signup(C,'Vic','vic@x.com')
    A.click('#nav button[data-p="admin"]'); A.wait_for_timeout(500)
    A.locator('.card:has-text("Ed") button:text-is("Approve")').first.click(); A.wait_for_timeout(700)
    A.locator('.card:has-text("Vic") button:text-is("Approve")').first.click(); A.wait_for_timeout(700)
    A.locator('select[aria-label="Access for Vic"]').select_option('viewer'); A.wait_for_timeout(700)
    B.reload(); B.wait_for_timeout(1500); C.reload(); C.wait_for_timeout(1500)
    ok('viewer nav: no Sprints, has Reports', C.locator('#nav button[data-p="sprints"]').count()==0 and C.locator('#nav button[data-p="reports"]').count()==1)
    C.click('#nav button[data-p="reports"]'); C.wait_for_timeout(500)
    ok('viewer sees only submitted report, read-only', C.locator('#pg-reports select[aria-label="Report"] option').count()==1 and 'Sprint 228' in C.locator('#pg-reports').inner_text() and C.locator('#pg-reports textarea:not([disabled]), #pg-reports .rline input:not([disabled])').count()==0 and C.locator('button:text-is("Submit to executives")').count()==0)
    C.goto(URL+'#/sprints'); C.wait_for_timeout(800); ok('viewer cannot open Sprints by URL', C.locator('#pg-sprints').is_hidden())
    B.click('#nav button[data-p="reports"]'); B.wait_for_timeout(500)
    ok('editor sees drafts and can submit', B.locator('#pg-reports select[aria-label="Report"] option').count()==2 and B.locator('button:text-is("Submit to executives")').count()==1)
    B.click('button:text-is("Submit to executives")'); B.wait_for_timeout(600); ok('editor submitted a report', 'Submitted' in B.locator('#pg-reports .rmeta').inner_text())
    ok('report shows week hero and tiles', B.locator('.rhero').count()==1 and B.locator('.rtile').count()==3 and 'week 2 of 2' in B.locator('.rhero').inner_text())
    C.reload(); C.wait_for_timeout(1500); C.click('#nav button[data-p="reports"]'); C.wait_for_timeout(500)
    ok('viewer now sees both submitted, visual read-only view', C.locator('#pg-reports select[aria-label="Report"] option').count()==2 and C.locator('.rprod.rview').count()==3)
    C.set_viewport_size({'width':390,'height':800}); C.click('#nav button[data-p="reports"]'); C.wait_for_timeout(400)
    ok('no overflow on phone', not C.evaluate("document.documentElement.scrollWidth>innerWidth+1"))

    # --- empty data: clear error, AI never called
    ctx2=mkctx(b); e2=[]; D=newpage(ctx2,e2); signup(D,'Admin','adm@x.com')
    D.click('#nav button[data-p="sprints"]'); D.click('button:text-is("+ New sprint")'); D.wait_for_timeout(400)
    D.click('#nav button[data-p="reports"]'); D.click('button:has-text("New report for week of")'); D.wait_for_timeout(700)
    ok('empty week shows a clear error', 'No data found' in D.locator('#pg-reports .rnote.bad').inner_text())
    D.click('button:has-text("Generate with AI")'); D.wait_for_timeout(600)
    ok('AI is not called without data', not D.evaluate("window.__aiCalls") and 'No data found' in D.locator('#pg-reports .rnote.bad').inner_text())
    ok('AI button is the sparkle button', D.locator('button.ai svg.spark').count()==1)
    # --- missing tables (SQL 06 not run): setup banner instead of an "offline" banner
    ctx3=mkctx(b, init="window.__missing=['reports']"); e3=[]; E=newpage(ctx3,e3); signup(E,'Admin','adm@x.com')
    E.click('#nav button[data-p="sprints"]'); E.click('button:text-is("+ New sprint")'); E.wait_for_timeout(300)
    E.locator('.sdoc .ghost .bt').click(); E.keyboard.press('/'); E.keyboard.type('Product'); E.keyboard.press('Enter'); E.keyboard.type('Tifli'); E.keyboard.press('Enter'); E.keyboard.type('Eve'); E.keyboard.press('Enter'); E.keyboard.type('Thing'); E.wait_for_timeout(700)
    E.click('#nav button[data-p="reports"]'); E.click('button:has-text("New report for week of")'); E.wait_for_timeout(1500)
    ok('missing table shows setup banner', 'Database setup needed' in E.locator('#pg-reports .rerr').inner_text())
    ok('missing table is not shown as offline', E.locator('#offbar').is_hidden())
    ok('no page errors', errs==[])
p=sum(1 for _,c in R if c); print(p,'/',len(R)); sys.exit(0 if p==len(R) else 1)
