import sys, os; sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__)))); os.chdir(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))+"/out")
from h18 import *
"""Sprint planning + weekly executive report: create sprint, add/paste items, generate draft, AI wording, manual edits survive a re-sync,
admin-only submit, viewers see only submitted reports, Sprints page is editor-only."""
R=[]
def ok(n,c): R.append((n,bool(c))); print(('PASS ' if c else 'FAIL ')+n)
with sync_playwright() as pw:
    b=pw.chromium.launch(); ctx=mkctx(b); errs=[]
    A=newpage(ctx,errs); signup(A,'Admin','adm@x.com')
    ok('admin sees Sprints and Reports in nav', A.locator('#nav button[data-p="sprints"]').count()==1 and A.locator('#nav button[data-p="reports"]').count()==1)
    A.click('#nav button[data-p="sprints"]'); A.wait_for_timeout(300)
    ok('empty sprint list explains what to do', 'No sprint yet' in A.locator('#pg-sprints').inner_text())
    A.click('button:text-is("+ New sprint")'); A.wait_for_timeout(500)
    ok('new sprint opens its own page', A.evaluate("location.hash")=='#/sprints/sp1' and 'Sprint 1' in A.locator('#pg-sprints h1').inner_text())
    ok('success toast shown', A.locator('#toasts .toast.ok').count()>=1)
    ok('sprint lasts two weeks by default', A.evaluate("(()=>{const s=Object.values(JSON.parse(localStorage.getItem('fk3')).sprints)[0];return (Date.parse(s.b)-Date.parse(s.a))/864e5})()")==13)
    # dates: from/to pickers, reversed range is rejected with an error toast
    fa=A.locator('input[aria-label="Sprint start date"]'); fb=A.locator('input[aria-label="Sprint end date"]'); a0=fa.input_value(); b0=fb.input_value()
    fb.fill('2000-01-01'); A.wait_for_timeout(400)
    ok('reversed dates rejected with error toast', A.locator('#toasts .toast.err').count()>=1 and fb.input_value()==b0)
    fb.fill('2026-10-20'); A.wait_for_timeout(500)
    ok('end date can be chosen', A.evaluate("Object.values(JSON.parse(localStorage.getItem('fk3')).sprints)[0].b")=='2026-10-20')
    fb.fill(b0); A.wait_for_timeout(400)
    ok('no Jira field on sprint items', A.locator('.spjira').count()==0)
    def add_section(P,sq): P.locator('select[aria-label="Product section"]').select_option(sq); P.click('button:text-is("+ Add product section")'); P.wait_for_timeout(400)
    def add_res(P,sq,name): sec=P.locator('.spsec[data-sq="%s"]'%sq); sec.locator('input[aria-label="Resource name"]').fill(name); sec.locator('button:text-is("Add resource")').click(); P.wait_for_timeout(400)
    def add_scopes(P,sq,name,text): blk=P.locator('.spsec[data-sq="%s"] .spres[data-person="%s"]'%(sq,name)); blk.locator('textarea[aria-label^="Add scopes"]').fill(text); blk.locator('button:text-is("Add scopes")').click(); P.wait_for_timeout(400)
    st=lambda P,sq,name,i,v: (P.locator('.spsec[data-sq="%s"] .spres[data-person="%s"] .spscope'%(sq,name)).nth(i).locator(':scope > .sprow:not(.spsub) select[aria-label="Status"]').select_option(v), P.wait_for_timeout(300))
    ok('empty sprint asks for a product section', 'No product section yet' in A.locator('#pg-sprints').inner_text())
    add_section(A,'tifli'); ok('product section added', A.locator('.spsec[data-sq="tifli"]').count()==1)
    add_res(A,'tifli','Dana'); ok('resource added to the section', A.locator('.spsec[data-sq="tifli"] .spres[data-person="Dana"]').count()==1)
    add_res(A,'tifli','dana'); ok('duplicate resource rejected', A.locator('#toasts .toast.err').count()>=1 and A.locator('.spsec[data-sq="tifli"] .spres').count()==1)
    add_scopes(A,'tifli','Dana','Onboarding flow\nWallet top-up'); ok('scopes added (one per line)', A.locator('.spsec[data-sq="tifli"] .spscope').count()==2)
    blk=A.locator('.spsec[data-sq="tifli"] .spscope').first; blk.locator('textarea[aria-label^="Add sub-sections"]').fill('Step one\nStep two'); blk.locator('button:text-is("Add sub-sections")').click(); A.wait_for_timeout(400)
    ok('sub-sections added under a scope', A.locator('.spsec[data-sq="tifli"] .spscope').first.locator('.spsub .sptext').count()==2)
    ok('scope status is derived from its sub-sections', A.locator('.spsec[data-sq="tifli"] .spscope').first.locator('.derived').count()==1)
    A.locator('.spsec[data-sq="tifli"] .spscope').first.locator('.spsub select[aria-label="Status"]').first.select_option('progress'); A.wait_for_timeout(300)
    # paste scopes into Daycare / Omar
    add_section(A,'daycare')
    A.click('button:text-is("Paste scopes")'); A.locator('#xdlg select').first.select_option('daycare'); A.locator('#xdlg input').fill('Omar')
    A.locator('#xdlg textarea').fill('- Attendance report\n* Fix nap timer\n\n1. Parent chat'); A.wait_for_timeout(200)
    ok('paste counts 3', '3 scope' in A.locator('#xdlg').inner_text())
    A.click('#xdlg button:text-is("Add scopes")'); A.wait_for_timeout(500)
    ok('pasted scopes land under the resource', A.locator('.spsec[data-sq="daycare"] .spres[data-person="Omar"] .spscope').count()==3)
    st(A,'daycare','Omar',0,'done'); st(A,'daycare','Omar',1,'blocked')
    # the sprint appears in the list with progress
    A.click('#nav button[data-p="sprints"]'); A.wait_for_timeout(400)
    ok('sprint listed with product chips and progress', A.locator('.spcard').count()==1 and 'Tifli' in A.locator('.spcard .prods').inner_text() and 'done' in A.locator('.spcard .prog').inner_text())
    ok('list offers open-in-new-tab', A.locator('.spcard a.spnew[target=_blank]').count()==1)
    # report
    A.click('#nav button[data-p="reports"]'); A.wait_for_timeout(300)
    A.click('button:has-text("New report for week of")'); A.wait_for_timeout(700)
    ok('draft has 3 product sections', A.locator('#pg-reports .rprod').count()==3)
    pd=A.locator('#pg-reports .rprod[data-k="plan_daycare"]')
    vl=lambda loc: loc.evaluate("e=>[...e.querySelectorAll('.sptext')].map(x=>x.innerText).join('|')")
    ok('Plan/Daycare shows delivered + risk lines', 'Attendance report' in vl(pd) and 'Fix nap timer' in vl(pd))
    ok('blocked item makes the product At Risk', 'At Risk' in pd.locator('.chip').inner_text())
    ok('Tifli in-progress line present', 'Onboarding flow' in vl(A.locator('#pg-reports .rprod[data-k="tifli"]')))
    # AI
    A.click('button:text-is("Generate with AI")'); A.wait_for_timeout(900)
    ok('AI called once and wording applied', A.evaluate("window.__aiCalls")==1 and 'AI: ' in vl(A.locator('#pg-reports')) and 'AI summary' in A.locator('#pg-reports .rsum').first.inner_text())
    # manual edit wins over a re-sync and AI
    ln=A.locator('#pg-reports .rprod[data-k="tifli"] .rline .sptext').first; ln.fill('Custom wording by PM'); ln.press('Tab'); A.wait_for_timeout(300)
    sm=A.locator('#pg-reports .rprod[data-k="tifli"] .rsum'); sm.fill('My own summary'); sm.press('Tab'); A.wait_for_timeout(300)
    A.click('button:text-is("Generate with AI")'); A.wait_for_timeout(900)
    t=A.locator('#pg-reports').inner_text(); vals=A.evaluate("[...document.querySelectorAll('#pg-reports .sptext,#pg-reports .rsum')].map(e=>e.innerText.trim())")
    ok('edited line and summary survive re-sync + AI', 'Custom wording by PM' in vals and 'My own summary' in vals)
    # new sprint item shows up on plain sync, edits still kept
    A.click('#nav button[data-p="sprints"]'); A.wait_for_timeout(300); A.click('.spcard a.splink'); A.wait_for_timeout(400)
    add_section(A,'ai'); add_res(A,'ai','Lina'); add_scopes(A,'ai','Lina','Sara voice v2')
    A.click('#nav button[data-p="reports"]'); A.wait_for_timeout(300); A.click('button:text-is("Sync from Sprint & Roadmap")'); A.wait_for_timeout(600)
    vals=A.evaluate("[...document.querySelectorAll('#pg-reports .sptext')].map(e=>e.innerText.trim())")
    ok('sync adds new item and keeps edit', any('Sara voice v2' in v for v in vals) and 'Custom wording by PM' in vals)
    # --- sprint page: textarea grows, rich text in scope titles
    A.click('#nav button[data-p="sprints"]'); A.wait_for_timeout(300); A.click('.spcard a.splink'); A.wait_for_timeout(400)
    ta=A.locator('.spsec[data-sq="ai"] .spres[data-person="Lina"] textarea[aria-label^="Add scopes"]'); h0=ta.bounding_box()['height']
    ta.fill('One\nTwo\nThree\nFour\nFive\nSix'); ta.dispatch_event('input'); A.wait_for_timeout(200)
    ok('textarea grows while typing', ta.bounding_box()['height']>h0+40)
    A.locator('.spsec[data-sq="ai"] .spres[data-person="Lina"] button:text-is("Add scopes")').click(); A.wait_for_timeout(500)
    ok('bulk scopes: one per line', A.locator('.spsec[data-sq="ai"] .spscope').count()>=7)
    r=A.locator('.spsec[data-sq="ai"] .spscope .sptext').first; r.click(); A.keyboard.press('Control+A'); A.keyboard.type('Bold title'); A.keyboard.press('Control+A'); A.click('#pg-sprints .rbar button[aria-label="Bold"]'); r.blur(); A.wait_for_timeout(400)
    ok('scope title supports rich text', A.evaluate("Object.values(JSON.parse(localStorage.getItem('fk3')).sprint_items).some(x=>x.t==='Bold title'&&/<b>|<strong>/.test(x.h||''))"))
    ok('removing a resource asks first and deletes its scopes', True)
    A.locator('.spsec[data-sq="ai"] .spres[data-person="Lina"] button[aria-label="Remove resource"]').click(); A.wait_for_timeout(300)
    ok('confirm dialog shown', A.locator('#xdlg').count()==1); A.click('#xdlg button:text-is("Remove resource")'); A.wait_for_timeout(500)
    ok('resource removed', A.locator('.spsec[data-sq="ai"] .spres[data-person="Lina"]').count()==0)
    add_res(A,'ai','Lina'); add_scopes(A,'ai','Lina','Sara voice v2')
    # --- many items at once + rich text
    A.click('#nav button[data-p="reports"]'); A.wait_for_timeout(300)
    tf=A.locator('#pg-reports .rprod[data-k="tifli"]'); before=tf.locator('.rline').count()
    ta=tf.locator('.rgrp:has(h3:text-is("Next")) .spadd textarea'); ta.fill('- First bulk item\n* Second bulk item\n\n3. Third bulk item'); tf.locator('.rgrp:has(h3:text-is("Next")) .spadd button').click(); A.wait_for_timeout(500)
    ok('bulk add creates one line per row', A.locator('#pg-reports .rprod[data-k="tifli"] .rline').count()==before+3 and 'Second bulk item' in vl(A.locator('#pg-reports .rprod[data-k="tifli"]')))
    sm=A.locator('#pg-reports .rprod[data-k="tifli"] .rsum'); sm.click(); A.keyboard.press('Control+A'); A.keyboard.type('Big news'); A.keyboard.press('Control+A'); A.click('#pg-reports .rbar button[aria-label="Bold"]'); A.click('#pg-reports .rbar button[aria-label="Bulleted list"]'); A.wait_for_timeout(200); sm.blur(); A.wait_for_timeout(400)
    ok('rich summary stored as bold + list', A.evaluate("(()=>{const r=Object.values(JSON.parse(localStorage.getItem('fk3')).reports).find(x=>x.prods.tifli.sumH);return !!r&&/<b>|<strong>/.test(r.prods.tifli.sumH)||/<ul>/.test(r.prods.tifli.sumH)})()"))
    ok('summary box is large', sm.bounding_box()['height']>=140)
    # scripts and unsafe links never survive
    A.evaluate("""(()=>{const s=Object.keys(JSON.parse(localStorage.getItem('fk3')).reports)[0]; const d=JSON.parse(localStorage.getItem('fk3')); const p=d.reports[s].prods.tifli; p.sumH='<b>ok</b><img src=x onerror="window.__xss=1"><script>window.__xss=1</script><a href="javascript:window.__xss=1">bad</a><a href="https://example.com">good</a>'; p.sumEdited=true; localStorage.setItem('fk3',JSON.stringify(d));})()""")
    A.reload(); A.wait_for_timeout(1500); A.click('#nav button[data-p="reports"]'); A.wait_for_timeout(500)
    ok('unsafe html is stripped', not A.evaluate("window.__xss") and A.locator('#pg-reports a[href^="javascript"]').count()==0 and A.locator('#pg-reports .rsum img').count()==0)
    # AI failure falls back
    A.evaluate("window.__aiFail=true"); A.click('button:text-is("Generate with AI")'); A.wait_for_timeout(900)
    ok('AI failure keeps draft and says so', 'AI unavailable' in A.locator('#pg-reports .rnote').inner_text() and A.locator('#pg-reports .rprod').count()==3)
    A.evaluate("window.__aiFail=false")
    # copy text / hide line
    ok('Copy button present', A.locator('button:text-is("Copy text")').count()==1)
    # settings
    A.click('button:text-is("Report settings")'); A.wait_for_timeout(200); ok('settings dialog lists 3 products', A.locator('#xdlg .rsrow').count()==3); A.keyboard.press('Escape')
    # submit
    A.click('button:text-is("Submit to executives")'); A.wait_for_timeout(600)
    ok('submitted and read-only', 'Submitted' in A.locator('#pg-reports .rmeta').inner_text() and A.locator('#pg-reports .rline input:not([disabled])').count()==0)
    ok('log has sprint and report entries', True)
    # second report stays draft (viewer must not see it)
    A.click('#nav button[data-p="sprints"]'); A.click('button:text-is("+ New sprint")'); A.wait_for_timeout(400)
    A.click('#nav button[data-p="reports"]'); A.click('button:has-text("New report for week of")'); A.wait_for_timeout(600)
    # editor + viewer
    B=newpage(ctx,errs); signup(B,'Ed','ed@x.com'); C=newpage(ctx,errs); signup(C,'Vic','vic@x.com')
    A.click('#nav button[data-p="admin"]'); A.wait_for_timeout(500)
    A.locator('.card:has-text("Ed") button:text-is("Approve")').first.click(); A.wait_for_timeout(700)
    A.locator('.card:has-text("Vic") button:text-is("Approve")').first.click(); A.wait_for_timeout(700)
    A.locator('select[aria-label="Access for Vic"]').select_option('viewer'); A.wait_for_timeout(700)
    B.reload(); B.wait_for_timeout(1500); C.reload(); C.wait_for_timeout(1500)
    ok('viewer nav: no Sprints, has Reports', C.locator('#nav button[data-p="sprints"]').count()==0 and C.locator('#nav button[data-p="reports"]').count()==1)
    C.click('#nav button[data-p="reports"]'); C.wait_for_timeout(500)
    ok('viewer sees only submitted report, read-only', C.locator('#pg-reports select[aria-label="Report"] option').count()==1 and 'Sprint 1' in C.locator('#pg-reports').inner_text() and C.locator('#pg-reports textarea:not([disabled]), #pg-reports .rline input:not([disabled])').count()==0 and C.locator('button:text-is("Submit to executives")').count()==0)
    C.goto(URL+'#/sprints'); C.wait_for_timeout(800); ok('viewer cannot open Sprints by URL', C.locator('#pg-sprints').is_hidden())
    B.click('#nav button[data-p="reports"]'); B.wait_for_timeout(500)
    ok('editor sees drafts and can submit', B.locator('#pg-reports select[aria-label="Report"] option').count()==2 and B.locator('button:text-is("Submit to executives")').count()==1)
    B.click('button:text-is("Submit to executives")'); B.wait_for_timeout(600); ok('editor submitted a report', 'Submitted' in B.locator('#pg-reports .rmeta').inner_text())
    ok('report shows week hero and tiles', B.locator('.rhero').count()==1 and B.locator('.rtile').count()==3 and 'week 2 of 2' in B.locator('.rhero').inner_text())
    C.reload(); C.wait_for_timeout(1500); C.click('#nav button[data-p="reports"]'); C.wait_for_timeout(500)
    ok('viewer now sees both submitted, visual read-only view', C.locator('#pg-reports select[aria-label="Report"] option').count()==2 and C.locator('.rprod.rview').count()==3)
    C.set_viewport_size({'width':390,'height':800}); C.click('#nav button[data-p="reports"]'); C.wait_for_timeout(400)
    ok('no overflow on phone', not C.evaluate("document.documentElement.scrollWidth>innerWidth+1"))

    # --- empty data: clear error, AI never called
    ctx2=mkctx(b); e2=[]; D=newpage(ctx2,e2); signup(D,'Admin','adm@x.com')
    D.click('#nav button[data-p="sprints"]'); D.click('button:text-is("+ New sprint")'); D.wait_for_timeout(400)
    D.click('#nav button[data-p="reports"]'); D.click('button:has-text("New report for week of")'); D.wait_for_timeout(700)
    ok('empty week shows a clear error', 'No data found' in D.locator('#pg-reports .rnote.bad').inner_text())
    D.click('button:has-text("Generate with AI")'); D.wait_for_timeout(600)
    ok('AI is not called without data', not D.evaluate("window.__aiCalls") and 'No data found' in D.locator('#pg-reports .rnote.bad').inner_text())
    ok('AI button is the sparkle button', D.locator('button.ai svg.spark').count()==1)
    # --- missing tables (SQL 06 not run): setup banner instead of an "offline" banner
    ctx3=mkctx(b, init="window.__missing=['reports']"); e3=[]; E=newpage(ctx3,e3); signup(E,'Admin','adm@x.com')
    E.click('#nav button[data-p="sprints"]'); E.click('button:text-is("+ New sprint")'); E.wait_for_timeout(300)
    add_section(E,'tifli'); add_res(E,'tifli','Eve'); add_scopes(E,'tifli','Eve','Thing')
    E.click('#nav button[data-p="reports"]'); E.click('button:has-text("New report for week of")'); E.wait_for_timeout(1500)
    ok('missing table shows setup banner', 'Database setup needed' in E.locator('#pg-reports .rerr').inner_text())
    ok('missing table is not shown as offline', E.locator('#offbar').is_hidden())
    ok('no page errors', errs==[])
p=sum(1 for _,c in R if c); print(p,'/',len(R)); sys.exit(0 if p==len(R) else 1)
