import sys, os; sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__)))); os.chdir(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))+"/out")
from h18 import *
R=[]
def ok(n,c): R.append((n,bool(c))); print(('PASS ' if c else 'FAIL ')+n)
def ctxmenu(p, sel, item):
    p.locator(sel).first.click(button='right'); p.wait_for_timeout(150); p.click('#ctx button:text-is("%s")'%item if not item.endswith('*') else '#ctx button:text-matches("^%s")'%item[:-1]); p.wait_for_timeout(300)
with sync_playwright() as pw:
    b=pw.chromium.launch(); ctx=mkctx(b); errs=[]
    A=newpage(ctx,errs); signup(A,'Admin','adm@x.com')
    B=newpage(ctx,errs); signup(B,'Engy','engy@x.com')
    approve(A); B.wait_for_timeout(16000)
    A.click('#nav button[data-p="roadmap"]'); A.wait_for_timeout(300)
    ok('B entered', B.locator('#nav button').count()>=8)
    # ---- presence
    A.wait_for_timeout(600)
    ok('A sees B online', A.locator('#presence .pav').count()==1 and 'Engy' in (A.locator('#presence').get_attribute('aria-label') or ''))
    bid=B.locator('.bar').first.get_attribute('data-id')
    B.locator('.bar[data-id="%s"]'%bid).first.dblclick(); B.wait_for_timeout(500); A.wait_for_timeout(400)
    ok('A sees lock chip', A.locator('.bar[data-id="%s"] .lockchip'%bid).count()>=1)
    A.locator('.bar[data-id="%s"]'%bid).first.dblclick(); A.wait_for_timeout(300)
    ok('A blocked with message', A.locator('input.bi').count()==0 and 'Engy is editing' in A.locator('#save').inner_text())
    A.locator('.bar[data-id="%s"]'%bid).first.dblclick(); A.wait_for_timeout(300)
    ok('A override on retry', A.locator('input.bi').count()==1)
    A.keyboard.press('Escape'); B.keyboard.press('Escape'); B.wait_for_timeout(500)
    ok('lock cleared', A.locator('.lockchip').count()==0)
    # ---- milestone + dependencies (A)
    A.reload(); A.wait_for_timeout(1200)
    ids=A.evaluate("[...new Set([...document.querySelectorAll('.bar')].map(b=>b.dataset.id))].slice(0,3)")
    a_id,b_id,c_id=ids
    ctxmenu(A,'.bar[data-id="%s"]'%c_id,'Make milestone')
    ok('milestone class', A.locator('.bar.ms[data-id="%s"]'%c_id).count()>=1)
    # dependency: b depends on a
    A.locator('.bar[data-id="%s"]'%b_id).first.click(button='right'); A.click('#ctx button:text-matches("^Depends on")'); A.wait_for_timeout(300)
    ok('dep dialog', A.locator('#xdlg').count()==1)
    A.locator('#xdlg .deprow input').first.check(); A.click('#xdlg button:text-is("Save")'); A.wait_for_timeout(500)
    ok('dep arrow drawn', A.locator('svg.ovl path.dep').count()>=1)
    ok('dep chip', A.locator('.depchip').count()==1)
    A.screenshot(path='v4_dep.png')
    # force clash: make dependency where successor starts before predecessor ends
    A.evaluate("()=>{}")
    print('chip text:',A.locator('.depchip').inner_text())
    # log entry for dep
    A.click('#nav button[data-p="log"]'); A.wait_for_timeout(300); ok('dep logged', 'depends on' in A.locator('#pg-log').inner_text())
    # ---- capacity
    A.click('#nav button[data-p="capacity"]'); A.wait_for_timeout(400)
    ok('capacity table', A.locator('.captable tbody tr').count()>=3 and A.locator('.capcell').count()>20)
    A.screenshot(path='v4_cap.png')
    print(A.locator('.captable tbody tr').first.inner_text()[:100].replace('\n',' '))
    # ---- baselines
    A.click('#nav button[data-p="baselines"]'); A.wait_for_timeout(300); A.click('button:text-is("Save snapshot")'); A.wait_for_timeout(600)
    ok('snapshot saved', A.locator('.snaprow').count()==1 and A.locator('.snaprow .badge:text-is("baseline")').count()==1)
    A.click('#nav button[data-p="roadmap"]'); A.wait_for_timeout(300)
    A.locator('.bar[data-id="%s"]'%a_id).first.press('ArrowRight'); A.locator('.bar[data-id="%s"]'%a_id).first.press('ArrowRight'); A.wait_for_timeout(500)
    ok('ghost btn visible', A.locator('#ghostbtn').is_visible())
    A.click('#ghostbtn'); A.wait_for_timeout(400)
    ok('ghost rect drawn', A.locator('svg.ovl rect.ghost').count()>=1)
    A.screenshot(path='v4_ghost.png')
    A.click('#nav button[data-p="baselines"]'); A.wait_for_timeout(300); A.click('button:text-is("Compare with now")'); A.wait_for_timeout(300)
    ok('compare shows moved', '1' in A.locator('.cmpbox .summary div').first.inner_text() and 'Moved' in A.locator('.cmpbox').inner_text())
    # ---- share
    A.click('#nav button[data-p="roadmap"]'); A.wait_for_timeout(300); A.click('#sharebtn'); A.wait_for_timeout(300); A.click('button:text-is("Create share link")'); A.wait_for_timeout(500)
    url=A.locator('#shareurl').input_value(); ok('share url', '#/share/' in url)
    S2=ctx.new_page(); S2.on('pageerror',lambda e:errs.append(str(e))); S2.goto(url); S2.wait_for_timeout(1200)
    ok('shared view loads bars', S2.locator('.bar').count()>10)
    ok('shared view read-only', not S2.locator('#add').is_visible() and S2.locator('.rail').is_visible()==False and 'read-only' in S2.locator('#offbar').inner_text())
    S2.locator('.bar').first.dblclick(); S2.wait_for_timeout(200); ok('shared no edit', S2.locator('input.bi').count()==0)
    S2.screenshot(path='v4_share.png')
    A.click('button:text-is("Stop sharing")'); A.wait_for_timeout(500)
    S2.goto(url); S2.wait_for_timeout(800); S2.reload(); S2.wait_for_timeout(800)
    ok('revoked link dead', 'not active' in S2.locator('#gate').inner_text())
    # ---- viewer role
    A.keyboard.press('Escape'); A.click('#nav button[data-p="admin"]'); A.wait_for_timeout(500)
    A.locator('select[aria-label="Access for Engy"]').select_option('viewer'); A.wait_for_timeout(600)
    B.reload(); B.wait_for_timeout(1500)
    ok('viewer nav limited', B.locator('#nav button').count()==4)
    ok('viewer cannot add', not B.locator('#add').is_visible())
    B.locator('.bar').first.dblclick(); B.wait_for_timeout(200); ok('viewer no edit', B.locator('input.bi').count()==0)
    B.screenshot(path='v4_viewer.png')
    print(errs)
    print(sum(1 for r in R if r[1]),'/',len(R))
